

# Found the correct command for the idea - might be worth a retry or little script: hyprctl keyword monitor HDMI-A-1,3840x2160@60,0x0,1.0
# $togglescreens = hyprctl keyword monitor HDMI-A-2, disabled; hyprctl keyword monitor HDMI-A-2, disabled; hyprctl keyword monitor DP-1, disabled; hyprctl keyword monitor $monhifi
# $togglepc = hyprctl keyword monitor $monwork; hyprctl keyword monitor $monmisc; hyprctl keyword monitor $monside; 
###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

{{- if eq .chezmoi.hostname "amanita" }}

$mon = DP-1
$ws = 1 
workspace = $ws, monitor:$mon, persistent:true, layoutopt:orientation:top
exec-once = [workspace $ws silent] obsidian
$ws = 2
workspace = $ws, monitor:$mon, persistent:true
# exec-once = [workspace $ws silent] ticktick 
# exec-once = [workspace $ws silent] $terminal #start $fileManager
# Doesn't work, at least not with how steam is currently configured
$ws = 3
workspace = $ws, monitor:$mon, persistent:true
# exec-once = [workspace $ws] steam 


$mon = DP-2
$ws = 4
workspace = $ws, monitor:$mon, persistent:true, default:true, name:main
# exec-once = [workspace special:browser] zen-browser
exec-once = [workspace $ws] flatpak run app.zen_browser.zen   # Flatpak
$ws = 5
workspace = $ws, monitor:$mon, persistent:true
# exec-once = [workspace $ws silent] $terminal 
$ws = 6
workspace = $ws, monitor:$mon, persistent:true
# exec-once = [workspace $ws silent] Placeholder


$mon = HDMI-A-2
$ws = 7
workspace = $ws, monitor:$mon, persistent:true, default:true, layoutopt:orientation:top
exec-once = [workspace $ws silent] slack & proton-mail & keepassxc & ticktick
# exec-once = sleep 4 && hyprctl dispatch resizewindowpixel exact 26% 38%,class:org.keepassxc.KeePassXC
$ws = 8 
workspace = $ws, monitor:$mon, persistent:true, layoutopt:orientation:top
exec-once = [workspace $ws silent] signal-messenger
# exec-once = hyprctl dispatch resizewindowpixel 100% 20%,class:^(org.pulseaudio.pavucontrol)$
$ws = 9
workspace = $ws, monitor:$mon, persistent:true
exec-once = [workspace $ws silent] spotify
exec-once = [workspace $ws silent] wezterm start pulsemixer

{{- end }}




# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {



# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]






###################
### PERMISSIONS ###
###################

# See https://wiki.hyprland.org/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow



#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    
}

# # https://wiki.hyprland.org/Configuring/Variables/#gestures




# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
# device {
#     name = epic-mouse-v1
#     sensitivity = -0.5
# }







