import GLib from "gi://GLib"
import AstalWp from "gi://AstalWp"
import { createState } from "ags"
import { execAsync } from "ags/process"
import { readFile } from "ags/file"
import { idle, timeout } from "ags/time"

// Which speaker the machine is playing through, and its volume. Read over
// AstalWp (GObject-Introspection onto WirePlumber, no subprocess); *changed* by
// shelling out to `audio-switch`, so the bar, the CTRL+SUPER+ALT+A keybind and
// the CLI all drive one implementation of "what comes next". See
// modules/home/audio-switch/.

const audio = AstalWp.get_default().audio

// AstalWp types the endpoint list as nullable — it is null before the
// WirePlumber connection is up. Nothing downstream cares about the difference
// between "no list yet" and "no speakers", so it is flattened here once.
function speakers(): AstalWp.Endpoint[] {
  return audio.get_speakers() ?? []
}

// ── The ring ─────────────────────────────────────────────────────────────────
// Declared in modules/home/audio-switch/default.nix and dropped here by
// home-manager. It cannot be handed to the bar as a store path the way it is to
// the script: ~/.config/ags is an out-of-store symlink into the working tree, so
// nothing in this directory is generated by Nix.

type RingEntry = { label: string; icon: string; re: RegExp }

const RING_PATH = "audio-switch/devices.json"

let ring: RingEntry[] = []

function readRing(): RingEntry[] {
  const path = `${GLib.get_user_config_dir()}/${RING_PATH}`
  let raw: Array<{ match: string; label: string; icon: string }>
  try {
    raw = JSON.parse(readFile(path))
  } catch (e) {
    // Not fatal: without the table every output falls back to its full PipeWire
    // description and the generic speaker glyph, which is worse-looking but
    // still correct. Only the click target would be missing, and that lives in
    // the binary, not here.
    console.error(`audio: no output ring at ${path} —`, e)
    return []
  }

  const entries: RingEntry[] = []
  for (const r of raw) {
    try {
      entries.push({ label: r.label, icon: r.icon, re: new RegExp(r.match) })
    } catch (e) {
      // A bad pattern must not take the widget with it — an exception thrown
      // from a GObject signal handler unwinds into C and kills the bar.
      console.error(`audio: ignoring unparseable ring pattern ${r.match} —`, e)
    }
  }
  return entries
}

// ── State ────────────────────────────────────────────────────────────────────

export type Output = {
  label: string
  icon: string // vocabulary key from the ring; Audio.tsx maps it to a glyph
  volume: number // 0-100
  mute: boolean
}

// null when nothing is default at all — every sink unplugged, or WirePlumber
// still starting.
const [output, setOutput] = createState<Output | null>(null)
export { output }

function describe(speaker: AstalWp.Endpoint): Output {
  const desc = speaker.description ?? ""
  const entry = ring.find((r) => r.re.test(desc))
  return {
    label: entry?.label ?? desc,
    icon: entry?.icon ?? "speaker",
    volume: Math.round(speaker.volume * 100),
    mute: speaker.mute,
  }
}

let lastSignature = ""

function recompute() {
  // NOT `audio.defaultSpeaker`. That property is real and readable, but it lags:
  // inside a notify::is-default handler it still reports the *previous* device,
  // and it catches up some turns later. The per-endpoint is-default flags are
  // what the signals actually describe, so they are what gets read.
  const speaker = speakers().find((s) => s.isDefault) ?? null
  const next = speaker ? describe(speaker) : null

  const signature = JSON.stringify(next)
  if (signature === lastSignature) return
  lastSignature = signature
  setOutput(next)
}

// Coalesced onto an idle tick. One switch emits two is-default notifications —
// true on the new device, false on the old — and between them the flags are
// briefly inconsistent: both set, or (switching the other way) neither. Reading
// once after the burst settles is what makes find() unambiguous.
let scheduled = false

function schedule() {
  if (scheduled) return
  scheduled = true
  idle(() => {
    scheduled = false
    recompute()
  })
}

// ── Subscriptions ────────────────────────────────────────────────────────────
// There is no single signal for "the default output changed": AstalWp declares a
// `default-speaker` property on both Wp and Audio and never emits notify:: for
// either of them. Watching each endpoint's own is-default flag is the only thing
// that fires — and it fires for an external `wpctl set-default` exactly as it
// does for one of ours, which is what lets the keybind update the bar for free.

// Keyed on the endpoint so a device coming or going disconnects the handlers it
// owned instead of stacking a second set on every survivor. GJS hands back the
// same JS wrapper for a given GObject, so identity works as a key.
const handlers = new Map<AstalWp.Endpoint, number[]>()

function resubscribe() {
  const live = new Set(speakers())

  for (const [endpoint, ids] of handlers) {
    if (live.has(endpoint)) continue
    for (const id of ids) endpoint.disconnect(id)
    handlers.delete(endpoint)
  }

  for (const endpoint of live) {
    if (handlers.has(endpoint)) continue
    handlers.set(endpoint, [
      endpoint.connect("notify::is-default", schedule),
      endpoint.connect("notify::volume", schedule),
      endpoint.connect("notify::mute", schedule),
    ])
  }

  schedule()
}

// ── Actions ──────────────────────────────────────────────────────────────────

// A wheel notch is a coarser gesture than a key repeat, so this steps further
// than the 2% on XF86AudioRaiseVolume — 20 notches end to end rather than 50.
const STEP = 0.05

// `steps` is signed: +1 for one notch up, -1 for one down.
export function adjustVolume(steps: number) {
  const speaker = speakers().find((s) => s.isDefault)
  if (!speaker) return
  // Capped at 1.0, matching the `-l 1` on the volume keybind — above it
  // WirePlumber applies software gain and the two controls would disagree about
  // where the top is.
  speaker.volume = Math.max(0, Math.min(1, speaker.volume + steps * STEP))
}

// Deliberately a subprocess rather than endpoint.set_is_default() here: which
// device is *next* is the ring's business, and the ring is the binary's. Doing
// it in-process would mean a second implementation that drifts from the keybind.
// Nothing needs to be updated afterwards — the resulting is-default notification
// comes back through the subscriptions above.
export function cycle() {
  execAsync(["audio-switch"]).catch((e) => console.error("audio: switch failed —", e))
}

// ── Init ─────────────────────────────────────────────────────────────────────

export function init() {
  ring = readRing()

  // Endpoints appear a few ms after the connection opens, so the list is
  // rebuilt whenever it changes rather than sampled once.
  audio.connect("notify::speakers", resubscribe)
  resubscribe()

  // A second read once WirePlumber has settled. The endpoints exist before its
  // default-nodes plugin has said which one is default, and that first answer
  // does not always arrive as a notification — without this the bar can open
  // naming the wrong device and stay wrong until the next switch.
  timeout(1000, recompute)
}
